import type { Metadata } from "next";
import { GuideFaq, GuideLayout, GuideSection } from "../../_components/guide-layout";

const PAGE_DESCRIPTION =
  "What singers mean by \"support\" — the abdominal engagement that powers a strong voice from the diaphragm instead of straining the throat.";

export const metadata: Metadata = {
  title: "Breath Support for Singers: What It Is and How to Feel It — Trenodo",
  description: PAGE_DESCRIPTION,
  alternates: { canonical: "/knowledge/vocals/breath-support" },
  openGraph: {
    title: "Breath Support for Singers: What It Is and How to Feel It",
    description: PAGE_DESCRIPTION,
    url: "/knowledge/vocals/breath-support",
    siteName: "Trenodo",
    type: "article",
  },
};

const FAQS = [
  {
    q: "Why does support matter so much?",
    a: "Without it, the throat ends up doing work it isn't built for — straining to produce volume and pitch that should come from breath pressure instead. Over time that strain is what causes vocal fatigue and, in bad cases, real damage.",
  },
  {
    q: "Should I feel my abs clench and hold still?",
    a: "No — that's the most common mistake. A static clench feels stable at first but becomes a limiting habit. Real support is a continuous, evenly-engaged push, not a single flex you lock into place.",
  },
  {
    q: "How do I check I'm doing it right?",
    a: "Rest a hand on your stomach while you sing a phrase. You should feel steady engagement the whole way through the phrase, releasing only when you breathe in again before the next one.",
  },
] as const;

const structuredData = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      headline: "Breath Support for Singers: What It Is and How to Feel It",
      description: PAGE_DESCRIPTION,
      author: { "@type": "Organization", name: "Trenodo" },
    },
    {
      "@type": "FAQPage",
      mainEntity: FAQS.map((faq) => ({
        "@type": "Question",
        name: faq.q,
        acceptedAnswer: { "@type": "Answer", text: faq.a },
      })),
    },
  ],
};

export default function VocalsBreathSupportPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
      />
      <GuideLayout
        category="Vocals"
        categoryHref="/knowledge/vocals"
        title="Breath Support for Singers: What It Is and How to Feel It"
        intro={`“Support” is a word every singing teacher uses constantly, and it means something specific: engaging your abdominal muscles to drive sound from the diaphragm, instead of pushing it from a tense throat.`}
      >
        <GuideSection title="Why support exists">
          <p>
            Sound needs air pressure behind it. Without support, that
            pressure gets generated by tightening the throat — which can
            work for a while, but strains the vocal cords and caps how much
            volume, range and control is actually available. Support moves
            that work down to the diaphragm and abdominal muscles, which are
            built for it, freeing the throat to just shape the sound.
          </p>
        </GuideSection>

        <GuideSection title="A simple way to feel it">
          <p>
            Sustain a hissing &ldquo;sss&rdquo; sound for several seconds and pay
            attention to your abdominal muscles — you&rsquo;ll feel them
            contracting to push the air out at a steady rate. That
            contraction is the exact sensation to reproduce while singing.
          </p>
        </GuideSection>

        <GuideSection title="Continuous, not a single clench">
          <p>
            The most common mistake is treating support like a single flex —
            tightening the abs once and holding them rigid. It feels stable
            in the moment, but it&rsquo;s a habit that limits control later, since
            a locked muscle can&rsquo;t make the small continuous adjustments
            singing actually needs. Real support is an even, sustained
            engagement held through the whole phrase you&rsquo;re singing,
            released as you breathe in, then re-engaged as you start
            singing again.
          </p>
          <p>
            A simple way to check: rest a hand on your stomach while you
            sing. You&rsquo;re looking for steady engagement for the length of the
            phrase, not a single squeeze followed by nothing.
          </p>
        </GuideSection>

        <GuideFaq items={FAQS} />
      </GuideLayout>
    </>
  );
}
