/**
 * The Worker's entry point (wrangler.jsonc "main"). It is the worker
 * OpenNext generates, unchanged for every request, plus one thing Next.js
 * can't express: a scheduled handler for the hourly cron.
 *
 * Plain JavaScript on purpose. .open-next/worker.js only exists after
 * `opennextjs-cloudflare build`, so a TypeScript file importing it breaks
 * `next build`'s type check in CI, and no ts-comment works both locally
 * (where the file exists) and in CI (where it doesn't).
 */

// Generated by `opennextjs-cloudflare build`.
import worker from "./.open-next/worker.js";

// The Durable Object classes OpenNext's worker exports. They have to be
// exported from the entry point for wrangler to find them.
export {
  DOQueueHandler,
  DOShardedTagCache,
  BucketCachePurge,
} from "./.open-next/worker.js";

const entry = {
  fetch: worker.fetch,

  /**
   * Runs on the cron in wrangler.jsonc. Hands a request to the Next app
   * in-process, so the job lives in an ordinary route handler
   * (app/api/cron/spotlight-emails) with the same bindings and helpers as
   * everything else. The secret never leaves the Worker.
   */
  async scheduled(_controller, env, ctx) {
    const request = new Request(new URL("/api/cron/spotlight-emails", env.APP_URL), {
      method: "POST",
      headers: { "x-cron-secret": env.BETTER_AUTH_SECRET ?? "" },
    });
    ctx.waitUntil(worker.fetch(request, env, ctx));
  },
};

export default entry;
